#pragma config(Sensor, S1,     lightSensor,         sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                           - Line Tracker -                                             *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program allows your taskbot to follow a line in reverse.                                         *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  The Light Sensor is attached to the back of the robot.                                          *|
|*    2)  Be sure to take readings of your Light Sensor over the light and dark areas.  Once you have     *|
|*        the values, add them and divide by 2 to find your threshold.  Then, use your threshold as a     *|
|*        comparison in your program.                                                                     *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port B                  motorB              NXT                 Right motor                         *|
|*    Port C                  motorC              NXT                 Left motor                          *|
|*    Port 1                  lightSensor         Light Sensor        Back mounted                        *|
\*---------------------------------------------------------------------------------------------------4246-*/

int light;
int HIGH = 30;
int LOW = 2;
int GREEN = 45;
int BLACK = 35;
int WHITE = 50;

task main()
{
	wait1Msec(50);                        // The program waits 50 milliseconds to initialize the light sensor.

	while(true)                           // Infinite loop
	{
		light = SensorValue[lightSensor];
		if(false && abs(SensorValue[lightSensor] - GREEN) <= 5) {
				motor[motorB] = 0;                  // Motor B is run at a 60 power level.
				motor[motorC] = 0;
		} else {
			if(abs(SensorValue[lightSensor] - BLACK) <= 5) { // If the Light Sensor reads a value less than 45:
				motor[motorB] = HIGH;                  // Motor B is run at a 60 power level.
				motor[motorC] = LOW;                  // Motor C is run at a 20 power level.
			} else {                              // If the Light Sensor reads a value greater than or equal to 45:
				motor[motorB] = LOW;                  // Motor B is run at a 20 power level.
				motor[motorC] = HIGH;                  // Motor C is run at a 60 power level.
			}
		}
	}
}
